apiVersion: apps/v1
kind: Deployment
metadata:
  name: visiosphere-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visiosphere-frontend
  template:
    metadata:
      labels:
        app: visiosphere-frontend
    spec:
      containers:
        - name: frontend
          image: visiosphere-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: visiosphere-frontend
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
